#research_task:
#  description: >
#    Conduct a thorough research about {topic}
#    Make sure you find any interesting and relevant information given
#    the current year is 2024.
#  expected_output: >
#    A list with 10 bullet points of the most relevant information about {topic}
#
#reporting_task:
#  description: >
#    Review the context you got and expand each topic into a full section for a report.
#    Make sure the report is detailed and contains any and all relevant information.
#  expected_output: >
#    A fully fledge reports with the mains topics, each with a full section of information.
#    Formated as markdown with out '```'

design_icon_task:
  description: >
    Conceptualize a new vector-style icon for the given concept: {concept}.
    Follow the below guideline to create this icon:
    - Icon should have a minimalist design with bold, evenly spaced lines.
    - Icon should represent the concept: {concept}.
    - Keep the icon minimalistic.
  expected_output: >
    A detailed description of the {concept} icon concept. Example: "IT Support: A headset with a computer"

generate_icon_task:
  description: >
    Create a vector-style icon based on the designer's description for the concept: {concept}.
    Follow the below guideline to create these icons:
    - Icon should have a minimalist design with bold, evenly spaced lines.
    - The lines should be in a red color with a thickness consistent throughout the icon.
    - Icon should represent the concept: {concept}.
    - Ensure the background is transparent to focus solely on the icon.
    - Use only red color HEX: #f8485e.
    - Icon should have a round circle.
    - Keep the icon minimalistic.
    - Background color should be pure white.
    - Don't use any other color but white and red.
  expected_output: >
    A vector-style icons image representing the {concept} as described by the Designer Agent.
    Each icon should be a high-quality image file with the specified guidelines.

evaluate_icon_task:
  description: >
    Evaluate the generated vector-style icons for the concept: {concept} to ensure they match existing Devoteam icons in style and quality.
    Compare them against the provided guidelines and score each icon out of 10. Use existing images 
    in directory to evaluated generated icons
  expected_output: >
    A list of scores for each generated icon, along with comments on their adherence to Devoteam's branding and quality standards.
    Example: Icon 1: 8/10 - Matches branding well but could use a clearer representation of the concept.

